version: "3.8"

services:
  jenkinks:
    container_name: jenkins
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    ports:
      - 5050:8080
      - 50000:50000
    volumes:
      - ./data/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
